/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mensajeria;

import java.util.Arrays;

/**
 *
 * @author Jespi_000
 */
public class Pantalla_principal extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_principal
     */
    public Pantalla_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelViewDinamico = new javax.swing.JPanel();
        visualizacionLabel = new javax.swing.JLabel();
        consolaLabel = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        consolaOldText = new javax.swing.JTextArea();
        consolaText = new javax.swing.JTextField();
        outputLabel = new java.awt.Label();
        outputText = new java.awt.TextArea();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Mensajería");
        setAlwaysOnTop(true);
        setName("VentanaPrincipal"); // NOI18N
        setResizable(false);

        PanelViewDinamico.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        visualizacionLabel.setText("Visualización de Estados y Logs");

        javax.swing.GroupLayout PanelViewDinamicoLayout = new javax.swing.GroupLayout(PanelViewDinamico);
        PanelViewDinamico.setLayout(PanelViewDinamicoLayout);
        PanelViewDinamicoLayout.setHorizontalGroup(
            PanelViewDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelViewDinamicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visualizacionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelViewDinamicoLayout.setVerticalGroup(
            PanelViewDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelViewDinamicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visualizacionLabel)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        consolaLabel.setText("Consola");

        consolaOldText.setEditable(false);
        consolaOldText.setBackground(new java.awt.Color(0, 0, 0));
        consolaOldText.setColumns(20);
        consolaOldText.setForeground(new java.awt.Color(0, 153, 255));
        consolaOldText.setLineWrap(true);
        consolaOldText.setRows(5);
        consolaOldText.setText("¡Bienvenido al sistema!");
        consolaOldText.setWrapStyleWord(true);
        consolaOldText.setCaretColor(new java.awt.Color(51, 153, 255));
        consolaOldText.setDisabledTextColor(new java.awt.Color(51, 153, 255));
        jScrollPane1.setViewportView(consolaOldText);

        consolaText.setBackground(new java.awt.Color(0, 0, 0));
        consolaText.setForeground(new java.awt.Color(0, 255, 51));
        consolaText.setText(">>> ");
        consolaText.setToolTipText("Aquí puede escribir las funciones permitidas por el sistema.");
        consolaText.setAlignmentX(0.0F);
        consolaText.setCaretColor(new java.awt.Color(0, 255, 0));
        consolaText.setName(""); // NOI18N
        consolaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consolaTextActionPerformed(evt);
            }
        });

        outputLabel.setText("Evaluación de la información ");

        outputText.setEditable(false);
        outputText.setMinimumSize(new java.awt.Dimension(100, 50));
        outputText.setPreferredSize(new java.awt.Dimension(100, 50));

        jMenu1.setText("File");
        menu.add(jMenu1);

        jMenu2.setText("Edit");
        menu.add(jMenu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelViewDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(0, 0, 0))
                    .addComponent(consolaText)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consolaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 239, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelViewDinamico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consolaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consolaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        consolaLabel.getAccessibleContext().setAccessibleName("ConsolaLabel");
        outputLabel.getAccessibleContext().setAccessibleName("Output");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consolaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consolaTextActionPerformed
        //Escuchar la entrada del usuario
        String entrada = new String();
        try {
            //Obtener la entrada del usuario quitandole los >>> 
            entrada = consolaText.getText().substring(4);
            //System.out.println("Entrada del usuario: " + entrada);
            
            //Limpiar el texto en consolaText
            consolaText.setText(">>> ");
            //Mover el texto a consolaOldText y scrollear hasta abajo
            consolaOldText.append("\n>>> " + entrada);
            consolaOldText.setCaretPosition(consolaOldText.getDocument().getLength());
            
            //Si la entrada del usuario no está dentro de los comandos permitidos entonces:
            if (!(Arrays.asList(Globales.ComandosSimplesPermitidos).contains(entrada))){
                //Mostrar el mensaje de error en outputText
                outputText.setText("Error: La acción digitada no es válida para el sistema.");
            }
            else {
                outputText.setText("Realizado con éxito.");
            }
        }
        catch(Exception e){
            System.out.println("Excepción.");
        }
    }//GEN-LAST:event_consolaTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelViewDinamico;
    private java.awt.Label consolaLabel;
    private javax.swing.JTextArea consolaOldText;
    private javax.swing.JTextField consolaText;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menu;
    private java.awt.Label outputLabel;
    private java.awt.TextArea outputText;
    private javax.swing.JLabel visualizacionLabel;
    // End of variables declaration//GEN-END:variables
}
