/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mensajeria;

import java.util.Arrays;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Andres
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        CSend.setVisible(false);
        CReceive.setVisible(false);        
        CIndirecto.setVisible(false);
        CDirecReceive.setVisible(false);        
        TCantFijo.setEditable(false);
        LFijo.setVisible(false);
        if (Globales.reset){
            LSeleccionCantProcesos.setVisible(false);
            TCantProcesos.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBienvenido = new javax.swing.JLabel();
        LSeleccionSinc = new javax.swing.JLabel();
        LSeleccionDirecc = new javax.swing.JLabel();
        BContinuar = new javax.swing.JButton();
        LSeleccionFormato = new javax.swing.JLabel();
        LSeleccionFormato1 = new javax.swing.JLabel();
        CSincronizacion = new javax.swing.JComboBox();
        CDireccionamiento = new javax.swing.JComboBox();
        CDisciplina = new javax.swing.JComboBox();
        CSend = new javax.swing.JComboBox();
        CReceive = new javax.swing.JComboBox();
        CIndirecto = new javax.swing.JComboBox();
        CDirecReceive = new javax.swing.JComboBox();
        LSeleccionCantProcesos = new javax.swing.JLabel();
        TCantProcesos = new javax.swing.JTextField();
        CLargo = new javax.swing.JComboBox();
        TCantFijo = new javax.swing.JTextField();
        LCola = new javax.swing.JLabel();
        TCola = new javax.swing.JTextField();
        LFijo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBienvenido.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        LBienvenido.setText("¡Bienvenido!");
        LBienvenido.setName(""); // NOI18N

        LSeleccionSinc.setText("Seleccione el tipo de sincronización deseado:");

        LSeleccionDirecc.setText("Seleccione el tipo de direccionamiento deseado:");

        BContinuar.setText("Continuar");
        BContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BContinuarActionPerformed(evt);
            }
        });

        LSeleccionFormato.setText("Seleccione el tipo de formato deseado:");

        LSeleccionFormato1.setText("Seleccione la disciplina de manejo de datos deseada:");

        CSincronizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Send", "Receive" }));
        CSincronizacion.setToolTipText("Debe escoger el tipo de sincronización requerido");
        CSincronizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CSincronizacion.setName(""); // NOI18N
        CSincronizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSincronizacionActionPerformed(evt);
            }
        });

        CDireccionamiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directo", "Indirecto" }));
        CDireccionamiento.setToolTipText("Selección de direccionamiento requerido.");
        CDireccionamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CDireccionamiento.setName(""); // NOI18N
        CDireccionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDireccionamientoActionPerformed(evt);
            }
        });

        CDisciplina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FIFO (First In - First Out)", "Prioridad" }));
        CDisciplina.setToolTipText("Modalidad de manejo de datos seleccionada.");
        CDisciplina.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CDisciplina.setName(""); // NOI18N
        CDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDisciplinaActionPerformed(evt);
            }
        });

        CSend.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blocking", "Non-Blocking" }));
        CSend.setToolTipText("Debe seleccionar la modalidad de envío que se desee");
        CSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSendActionPerformed(evt);
            }
        });

        CReceive.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blocking", "Non-Blocking", "Prueba de llegada" }));
        CReceive.setToolTipText("Debe seleccionar la modalidad de de recibo de mensajes deseada.");

        CIndirecto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estático", "Dinámico" }));
        CIndirecto.setToolTipText("Modalidad de direccionamieno indrecto deseada.");
        CIndirecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIndirectoActionPerformed(evt);
            }
        });

        CDirecReceive.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Receive Explícito", "Receive Implícito" }));
        CDirecReceive.setToolTipText("Tipo de emisor deseado.");
        CDirecReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDirecReceiveActionPerformed(evt);
            }
        });

        LSeleccionCantProcesos.setText("Seleccione la cantidad de procesos por utilizar:");

        TCantProcesos.setToolTipText("Debe ingresar el númerro (2 a 6) de procesos que desea utillizar en la ejecución.");
        TCantProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCantProcesosActionPerformed(evt);
            }
        });

        CLargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Variable", "Fijo" }));
        CLargo.setToolTipText("Formato de colas que se desee.");
        CLargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLargoActionPerformed(evt);
            }
        });

        TCantFijo.setToolTipText("Cantidad de caracteres del largo de cada mensaje.");

        LCola.setText("Tamaño de la cola:");

        TCola.setToolTipText("Cantidad de elementos en la cola de mensajes.");
        TCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TColaActionPerformed(evt);
            }
        });

        LFijo.setText("Tamaño fijo de mensaje:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LSeleccionSinc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(LBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LSeleccionCantProcesos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CDireccionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CSincronizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(84, 84, 84))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(CDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(140, 140, 140)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LSeleccionFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CSend, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CDirecReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CIndirecto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(BContinuar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LSeleccionDirecc)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LSeleccionFormato1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TCola, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LCola)
                                            .addComponent(TCantFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LFijo))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TCantProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(LSeleccionCantProcesos)
                .addGap(9, 9, 9)
                .addComponent(TCantProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LSeleccionSinc)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CSincronizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CReceive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LSeleccionDirecc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CDireccionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CIndirecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CDirecReceive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LSeleccionFormato)
                    .addComponent(LFijo))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCantFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LSeleccionFormato1)
                    .addComponent(LCola))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BContinuar))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BContinuarActionPerformed
        boolean PuedeContinuar = true;
        //GET CANT PROCESOS
        if (!(Globales.reset)){
            try{
                int numProcesos = Integer.parseInt(TCantProcesos.getText());
                if ((1 < numProcesos)&& (numProcesos < 7)){
                    Globales.Procesos = numProcesos;
                }
                else{
                    PantallaError Error = new PantallaError("Debe ingresar un número entre 2 y 6 en el campo del número de procesos.");
                    PuedeContinuar = false;
                }
            }
            catch(Exception e){
                PantallaError Error = new PantallaError("Debe ingresar un número entre 2 y 6 en el campo del número de procesos  para continuar.");
                PuedeContinuar = false;
            }
        }
        //GET RECEIVE
        try{
            Globales.Receive = CReceive.getSelectedItem().toString();
        }
        catch(Exception e){
            PantallaError Error = new PantallaError("Debe configurar la sincronización Receive para continuar.");            
            PuedeContinuar = false;
        }
        //GET SEND
        try{
            switch (CSend.getSelectedItem().toString()){
                case "Blocking":
                    Globales.SendBlocking = true;
                    break;
                case "Non-Blocking":
                    Globales.SendBlocking = false;
                    break;
            }
        }
        catch(Exception e){
            PantallaError Error = new PantallaError("Debe configurar la sincronización Send para continuar.");            
            PuedeContinuar = false;
        }
        //GET DIRECCIONAMIENTO FALTA EL INDIRECTO
        try{
            if (CDireccionamiento.getSelectedItem().toString().equals("Directo")){
                Globales.DireccionamientoDirecto = true;
                if (CDirecReceive.getSelectedItem().toString().equals("Receive Explícito")){
                    Globales.ReceiveExplicito = true;
                }
                else{
                    Globales.ReceiveExplicito = false;
                }
            }
            else{
                Globales.DireccionamientoDirecto = false;
                if (CIndirecto.getSelectedItem().toString().equals("Estático")){
                    Globales.IndirectoEstatico = true;
                }
                else{
                    Globales.IndirectoEstatico = false;
                }
            }            
        }
        catch(Exception e){
            PantallaError Error = new PantallaError("Debe configurar la sincronización de Direccionamiento completamente para continuar.");
            PuedeContinuar = false;
        }
        //GET FORMATO VALIDAR LARGO 10-140 num entero
        try{
            if (CLargo.getSelectedItem().toString().equals("Fijo")){
                Globales.LargoMsjFijo = true;
                if ((Integer.parseInt(TCantFijo.getText()) < 10) || (Integer.parseInt(TCantFijo.getText()) > 140)){
                    PantallaError Error = new PantallaError("El largo del formato de los mensajes debe ser entre 10 y 140 caracteres.");
                    PuedeContinuar = false;
                }
                else{
                    Globales.LargoMsj = Integer.parseInt(TCantFijo.getText());
                }
            }
            else{
                Globales.LargoMsjFijo = false;
            }
        }
        catch (Exception e){
            PantallaError Error = new PantallaError("Debe configurar el Formato (largo) de los mensajes completamente para continuar.");
            PuedeContinuar = false;
        }
        //GET DISCIPLINA 
        try{
            if (CDisciplina.getSelectedItem().toString().equals("Prioridad")){
                Globales.FIFO = false;
            }
            else{
                Globales.FIFO = true;
            }
        }
        catch (Exception e){
            PantallaError Error = new PantallaError("Debe especificar la disciplina (FIFO o Prioridad) de la cola para continuar.");
            PuedeContinuar = false;
        }
        //GET TAMANO COLA 1-20 num entero
        try{
            if ((Integer.parseInt(TCola.getText()) < 1) || (Integer.parseInt(TCola.getText().toString()) > 20)){
                PantallaError Error = new PantallaError("El largo de la cola debe ser de 1-20.");
                PuedeContinuar = false;
            }
            else{
                Globales.TamanoCola = Integer.parseInt(TCola.getText());
            }
        }
        catch (Exception e){
            PantallaError Error = new PantallaError("Debe especificar el largo de la cola para continuar, y esta debe ser de largo 1-20.");
            PuedeContinuar = false;
        }
        if (PuedeContinuar == true){
            //Set texto de ayuda dinámico
            SetTextoAyuda();
            //Pida los nombres de los procesos
            if (!(Globales.reset)){
                SetNombresDeProcesos();
                //Tire pantalla de exito con: create() fue realizado
                PantallaExito exitoCreate = new PantallaExito("Create() realizado con éxito.\nLos procesos y elementos que especificó fueron creados con sus configuraciones.");
            }
            else{
                PantallaExito exitoCreate = new PantallaExito("Las configuraciones fueron cambiadas exitosamente y los logs reiniciado.");
            }
            this.setVisible(false);
            //Cerrar esta ventana y tirar ventana de consola
            if ((Globales.reset) && (!(Globales.DireccionamientoDirecto)) && (Globales.IndirectoEstatico)){
                for (int i = 0;i<Globales.Procesos;i++){
                    Mailbox mb = new Mailbox("MB"+Globales.procs[i].nombre);
                    Globales.mails[Globales.UltimoIndiceMailbox]=mb;
                    Globales.UltimoIndiceMailbox++;
                    Globales.procs[i].conectar(mb.nombre);
                }
            }
            Pantalla_principal Pantalla_Principal = new Pantalla_principal();
            Pantalla_Principal.setVisible(true);
            this.setEnabled(false);
        }
    }//GEN-LAST:event_BContinuarActionPerformed

    private void CSincronizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSincronizacionActionPerformed
        // TODO add your handling code here:        
        String valor=CSincronizacion.getSelectedItem().toString();
        if (valor.equals("Send")){
        CSend.setVisible(true);
        CReceive.setVisible(false);
        }
        else if (valor.equals("Receive")){
        CReceive.setVisible(true);
        CSend.setVisible(false);
        }
            
    }//GEN-LAST:event_CSincronizacionActionPerformed

    private void CDireccionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDireccionamientoActionPerformed
        // TODO add your handling code here:
        String valor=CDireccionamiento.getSelectedItem().toString();
        switch (valor) {
            case "Directo": 
                CDirecReceive.setVisible(true);
                CIndirecto.setVisible(false);
                break;
            case "Indirecto":
                CIndirecto.setVisible(true);
                CDirecReceive.setVisible(false);
                break;
        }
        
    }//GEN-LAST:event_CDireccionamientoActionPerformed

    private void CDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDisciplinaActionPerformed

    private void CDirecReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDirecReceiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDirecReceiveActionPerformed

    private void CDirectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDirectoActionPerformed
       
    }//GEN-LAST:event_CDirectoActionPerformed

    private void CSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSendActionPerformed

    public void SetTextoAyuda(){
        //Adaptar el texto de ayuda de acuerdo con las variables de configuración al momento
        String Texto = "Bienvenido a la Sección de Ayuda \nRecuerde escribir sin espacios.\nLista de comandos que puede ejecutar:\n - view(): Permite observar todo lo que está ocurriendo en el sistema mediante la sección de Visualización de Estados y Logs.\n - reset(): Reinicia el sistema y permite reconfigurarlo.";
        if (Globales.DireccionamientoDirecto){
            if (Globales.FIFO){
                Texto += "\n - send(NombreDelProcesoEmisor,NombreDelProcesoReceptor,Mensaje)";
                Texto += ": Envía un mensaje a un proceso.";
                if (Globales.LargoMsjFijo){
                    Texto += "El mensaje no debe sobrepasar los "+Globales.LargoMsj+" caracteres.";
                }
            }
            else{
                Texto += "\n - send(NombreDelProcesoEmisor,NombreDelProceso,Mensaje,NúmeroDePrioridad)";
                Texto += ": Envía un mensaje a un proceso con cierta prioridad (1,2 o 3, con 1 la más alta).";
                if (Globales.LargoMsjFijo){
                    Texto += "El mensaje no debe sobrepasar los "+Globales.LargoMsj+" caracteres.";
                }
            }
            if (Globales.ReceiveExplicito){
                Texto += "\n - receive(NombreDelProcesoReceptor,NombreDelProcesoEmisor)";
                Texto += ": Recibir un mensaje de un proceso.";
            }
            else{
                Texto += "\n - receive(NombreDelProcesoReceptor)";
                Texto += ": Recibir un mensaje del proceso que le envió previamente.";
            }
        }
        else{
            if (Globales.FIFO){
                Texto += "\n - send(NombreDelProcesoEmisor,NombreDelBuzón,Mensaje)";
                Texto += ": Envía un mensaje a un buzón.";
                if (Globales.LargoMsjFijo){
                    Texto += "El mensaje no debe sobrepasar los "+Globales.LargoMsj+" caracteres.";
                }
            }
            else{
                Texto += "\n - send(NombreDelProcesoEmisor,NombreDelBuzón,Mensaje,NúmeroDePrioridad)";
                Texto += ": Envía un mensaje a un buzón con cierta prioridad (1,2 o 3, con 1 la más alta).";
                if (Globales.LargoMsjFijo){
                    Texto += "El mensaje no debe sobrepasar los "+Globales.LargoMsj+" caracteres.";
                }
            }
            if (Globales.ReceiveExplicito){
                Texto += "\n - receive(NombreDelProcesoReceptor,NombreDelProcesoDeOrigen)";
                Texto += ": Recibe un mensaje del buzón suscrito del proceso de origen especificado.";
            }
            else{
                Texto += "\n - receive(NombreDelProcesoReceptor)";
                Texto += ": Recibe un mensaje del buzón suscrito.";
            }
            if (!(Globales.IndirectoEstatico)){
                Texto += "\n - create_mailbox(NombreDelBuzón)";
                Texto += ": Crea un buzón.";
            }
            Texto += "\n - connect_mailbox(NombreDelBuzón,NombreDelProcesoAConectar)";
            Texto += ": Conectar el proceso en referencia a cierto buzón.";
            Texto += "\n - disconnect_mailbox(NombreDelBuzón,NombreDelProcesoADesconectar)";
            Texto += ": Desonectar el proceso en referencia de cierto buzón.";
        }
        Globales.TextoAyuda = Texto;
    }
    
    private void CLargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLargoActionPerformed
        // TODO add your handling code here:        
        String valorCLargo=CLargo.getSelectedItem().toString();
        switch (valorCLargo) {
            case "Fijo":
                TCantFijo.setEditable(true);
                TCantFijo.setVisible(true);
                LFijo.setVisible(true);
                break;
            case "Variable":
                TCantFijo.setVisible(false);
                LFijo.setVisible(false);
                break;
        }
    }//GEN-LAST:event_CLargoActionPerformed

    private void TCantProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCantProcesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCantProcesosActionPerformed

    private void TColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TColaActionPerformed

    private void CIndirectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIndirectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIndirectoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);         
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BContinuar;
    private javax.swing.JComboBox CDirecReceive;
    private javax.swing.JComboBox CDireccionamiento;
    private javax.swing.JComboBox CDisciplina;
    private javax.swing.JComboBox CIndirecto;
    private javax.swing.JComboBox CLargo;
    private javax.swing.JComboBox CReceive;
    private javax.swing.JComboBox CSend;
    private javax.swing.JComboBox CSincronizacion;
    private javax.swing.JLabel LBienvenido;
    private javax.swing.JLabel LCola;
    private javax.swing.JLabel LFijo;
    private javax.swing.JLabel LSeleccionCantProcesos;
    private javax.swing.JLabel LSeleccionDirecc;
    private javax.swing.JLabel LSeleccionFormato;
    private javax.swing.JLabel LSeleccionFormato1;
    private javax.swing.JLabel LSeleccionSinc;
    private javax.swing.JTextField TCantFijo;
    private javax.swing.JTextField TCantProcesos;
    private javax.swing.JTextField TCola;
    // End of variables declaration//GEN-END:variables

    public void SetNombresDeProcesos() {
        for (int i=0;i<Globales.Procesos;i++){
            int numeroDeProcesoEnCuestion = i+1;
            String nombre = (String)JOptionPane.showInputDialog(new JFrame(),"Escriba el nombre del proceso #"+numeroDeProcesoEnCuestion,"Nombrar Procesos",JOptionPane.PLAIN_MESSAGE);
            //System.out.println("Proceso #"+numeroDeProcesoEnCuestion+" = "+nombre);
            while ((nombre==null) || (nombre.equals("")) || (MapeadorFunciones.IsProceso(nombre))){
                nombre = (String)JOptionPane.showInputDialog(new JFrame(),"El nombre que escribió ya está asignado a un proceso o no tenía caracteres.\nEscriba otro nombre para el proceso #"+numeroDeProcesoEnCuestion,"Nombrar Procesos",JOptionPane.PLAIN_MESSAGE);    
            }
            Proceso p = new Proceso(nombre);
            Globales.procs[i]=p;
        }
    }
}
